
name: Build README from JSON
on:
  push:
    branches: [ "main" ]
    paths:
      - "data/resume.json"
      - "build_readme.py"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build README
        run: |
          python build_readme.py
      - name: Commit README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: rebuild README from JSON" || echo "No changes"
          git push
